version: "3"

vars:
  DATABASE_URL: "postgres://postgres:foobarbaz@localhost:5432/postgres"
  IMAGE_REPO: twilight4/api-golang
  IMAGE_TAG: foobarbaz
  SERVICE_RELEASE_TAG: services/go/api-golang

includes:
  utils:
    taskfile: ../../../utils/Taskfile.yaml
    dir: ../../../utils

tasks:
  build-container-image:
    desc: Build container image
    cmds:
      - |
        docker build \
          -t={{.IMAGE_TAG}} \
          .

  build-container-image-multi-arch:
    desc: Build multi-arch container image
    cmds:
      - |
        docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} \
        --push \
        .

  install:
    desc: "download dependencies"
    cmds:
      - go mod tidy

  install-ci:
    desc: install/download package dependencies
    cmds:
      - go mod download

  test:
    desc: run tests
    cmds:
      - go test ./test -v
