version: "3"

tasks:
  install:
    desc: "download dependencies"
    cmds:
      - go mod tidy

  install-ci:
    desc: install/download package dependencies
    cmds:
      - go mod download

  test:
    desc: run tests
    cmds:
      - go test ./test -v
