version: "3"

tasks:
  install:
    desc: install dependencies
    cmds:
      - npm install

  install-ci:
    desc: install/download package dependencies
    cmds:
      - npm ci

  test:
    desc: run tests
    cmds:
      - npm run test
